### ISSUE TITLE
Fractional Seconds within DATETIME(3) / DATETIME(6) may result in syncing issues

### ISSUE THREAD

**Issue by orware** [planetscale/airbyte-source#55]
Related to [airbyte-source#50](https://github.com/planetscale/airbyte-source/issues/50).
[MySQL Fractional Seconds Documentation](https://dev.mysql.com/doc/refman/8.0/en/fractional-seconds.html)

One of our users that has been helpful in uncovering several other Airbyte issues in recent months has shared with us that they have had difficulty using the `Incremental | Deduped + History` option within Airbyte for their tables, although performing a `Full Sync` seems to work correctly.

In the logs provided to us via ticket, there were entries that looked like this related to the `DATETIME(3)` values they have in their table and the values may be causing a parsing issue since they do not match any of the known types mentioned in the link shared in [pr#51](https://github.com/planetscale/airbyte-source/pull/51).
```
2022-11-01 09:36:07 [1;31mERROR[m c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: No timezone information: 2022-11-01 09:35:29.717
2022-11-01 09:36:07 [1;31mERROR[m c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: No timezone information: 2022-11-01 09:35:29.717
2022-11-01 09:36:07 [1;31mERROR[m c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: No timezone information: 2022-11-01 09:35:29.717
```

At the moment I'm assuming that the regular `DATETIME` type may be handled correctly, but these fractional variations may not yet, although I cannot easily confirm that via my own testing quickly.

I'll see if I can replicate this issue as well, but I'd need to get Airbyte setup to run those tests, so this issue is primarily based on the current user report via ticket.

**Comment by orware** [comment]
This could also be an issue that's not on our end but in let's say the BigQuery Destination connector being used by the user in this case, but I really have little insight into the whole Airbyte workflow/process so it's difficult to share things in a definitive way without setting up an Airbyte environment and testing this myself which is what I can try and do, but it may not be a quick process for me to work through.

**Comment by hiramhuang** [comment]
I'm having the same exact error in the same exact configuration even when I using Full Sync mode.

**Comment by dikkeduif** [comment]
We're actually doing a full sync at the moment each hour to ensure the data is properly copied to BigQuery. As our data starts to grow this becomes problematic. Ideally we want to sync our data every x minutes, because the data is used for reporting and some of our dashboards.

Any resolution to this issue would be greatly appreciated. I've provided already the table structures and logs to planetscale support to reproduce the issue.

Since the only way to sync data out of Planetscale is with the connector, I feel this is really urgent.
