### ISSUE TITLE
Small number of rows come across with their positional index values from an ENUM column during an incremental sync

### ISSUE THREAD

**Issue by orware** [planetscale/airbyte-source#56]
This was reported by one of our users earlier this week and their experience is shared below:

> When syncing data from an `ENUM` column to BigQuery as a `STRING` column, a small number of the rows (approx. 25 out of 591,444)  appear within BigQuery with incorrect values.
> 
> **For example:**
> An `ENUM` column in the PlanetScale database named `type` has two types of values `MY_TYPE_A` and `MY_TYPE_B`.
> 
> Most rows synced to BigQuery have the correct string value set: `MY_TYPE_A` or `MY_TYPE_B`. 
> 
> For the small number of rows that across incorrectly, they arrived in BigQuery with the string values of either `1` or `2`.
> 
> Additional Airbyte Configuration Information:
> 
> - Normalization: Normalized tabular data (no custom transformers)
> - Sync mode: Incremental | Deduped + history

Based on what I'm reading on the [MySQL ENUM documentation](https://dev.mysql.com/doc/refman/8.0/en/enum.html), the `1` and `2` values correspond with the position index within the `ENUM` definition for the column so somehow Airbyte is picking up those numeric values rather than the string values they correspond to.

I had the user attempt a `Full Refresh` type sync as well to see if that could be a temporary solution, and that did appear to work correctly, so there may be something related to the way an `Incremental` sync gets handled that explains how this can happen.

Similar to [issue#55](https://github.com/planetscale/airbyte-source/issues/55), it is a bit difficult to know for sure if this is an issue within our connector itself or elsewhere in the way Airbyte processes the synchronization to BigQuery.

**Comment by akhil-consensys** [comment]
We are getting similar issues when syncing data from ENUM column in PlanetScale to Redshift. During incremental run, Airbyte is syncing the numeric (position) index rather than the actual value. This issue doesn't occur during a full refresh.
However, it is not possible to run a full refresh in production to sync millions of rows.

**Comment by notfelineit** [comment]
I believe we fixed this in https://github.com/planetscale/airbyte-source/pull/92 . Closing this issue now - if this persists, please let us know.
