### ISSUE TITLE
This connector no longer works with the lastest version of Airbyte

### ISSUE THREAD

**Issue by cwidafor** [planetscale/airbyte-source#58]
Hi!
I was setting up a new machine to host airbyte for the purpose of syncing Pscale -> Big Query. I have another machine doing the same thing that I spun up in December and it worked great. However, it looks like the latest version of Airbyte is no longer compatible with the code in this repo.

Two things to note:
1. The instructions for setting up a self hosted Airbyte instance is also out of dock. You will get an error for a file that does not exist. I manually added that file to get past the `composer up` error I was getting.

2. After setting up this repo as the src for a customer Airbyte Source, it will fail and give you this splash screen:
<img width="620" alt="Screen Shot 2023-01-29 at 4 45 44 PM" src="https://user-images.githubusercontent.com/27984292/215358295-f0b8a510-7fdf-48ad-b359-46604c9e991e.png">

It looks like it could be related to [this change](https://github.com/airbytehq/airbyte/pull/20146)

Would love to help contribute on a solution, but don't have the time to dig in this week. Wanted to take the time to make you guys aware because I love Pscale and really want this to work!

Thanks

**Comment by Phanatic** [comment]
Thanks for reporting this @cwidafor, I'm looking into it now.
